### ISSUE TITLE
Crash on 1.19.3 with new version of ShowKeybinds

### ISSUE THREAD

**Issue by voidrinix** [SJKZ1-2565/CheesySlot#14]
Hello, here is the crash report  https://mclo.gs/4EMD6ET 
It only happens on 1.19.3 for me, for 1.19.2 everything is ok

Also, when I join a world, a message appears in the chat saying that the mod is out of date, but I'm using the latest version.

**Comment by SJKZ1-2565** [comment]
It's seems not compatible with some mod

**Comment by voidrinix** [comment]
> It's seems not compatible with some mod

Oh, ok, I'll try to determine which mod cause that

**Comment by SJKZ1-2565** [comment]
Maybe mod that about item rendering I'm not sure tho, cause you have a tons of mods.

**Comment by voidrinix** [comment]
> Maybe mod that about item rendering I'm not sure tho, cause you have a tons of mods.

it crashes on empty instance with only show keybinds installed
https://mclo.gs/x8bP9YW

**Comment by SJKZ1-2565** [comment]
Well maybe you need to delete my mod and wait for next release!

**Comment by voidrinix** [comment]
> Well maybe you need to delete my mod and wait for next release!

I'll use 2.0.2 version, it works fine
