### ISSUE TITLE
Says mod is outdated even though it is up to date

### ISSUE THREAD

**Issue by rbits0** [SJKZ1-2565/CheesySlot#16]
![2023-03-11_16 12 50](https://user-images.githubusercontent.com/56014573/224466309-4fb96077-46a5-4739-800c-998acfe9cb4b.png)
![2023-03-11_16 12 58](https://user-images.githubusercontent.com/56014573/224466312-2364141c-21b7-4c96-a965-2fae5cf75b2c.png)

**Comment by SJKZ1-2565** [comment]
Will fix it in 2.0.5
