### ISSUE TITLE
Add support for 1.19.4 pls

### ISSUE THREAD

**Issue by voidrinix** [SJKZ1-2565/CheesySlot#17]

**Comment by SJKZ1-2565** [comment]
Soon, cause my computer seems broken a bit

**Comment by voidrinix** [comment]
> Soon, cause my computer seems broken a bit

Oh, I hope that everything is normal and that the problems are not serious. I can try to help and make a pull request

**Comment by voidrinix** [comment]
I made all things for update, but I got ```A problem occurred evaluating project ':fabric'. Could not find method classifier() for arguments [dev-shadow] on task ':fabric:shadowJar' of type com.github.jengelman.gradle.plugins.shadow.tasks.ShadowJar.``` error and I can't figure it out. If my changes will be useful I may send a pull request.

**Comment by SJKZ1-2565** [comment]
I'll handle everything don't worry stay tune :).
