### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by RinixGG** [SJKZ1-2565/CheesySlot#2]
Hello! After the last update (1.0.5) the arrangement of the numbers in the inventory is broken.

![Безымянный](https://user-images.githubusercontent.com/73175330/200112565-1fde40b6-8905-47f7-b326-f163524cc2a7.png)

**Comment by SJKZ1-2565** [comment]
Could you please give me your container text scale?

**Comment by RinixGG** [comment]
> Could you please give me your container text scale?

0.6

**Comment by SJKZ1-2565** [comment]
Ty!
