### ISSUE TITLE
Bug on Linux

### ISSUE THREAD

**Issue by RinixGG** [SJKZ1-2565/CheesySlot#3]
Hello! Today I noticed that mod doesn't work correctly on Linux. Here is the MC screenshot and system info
![2022-11-26_22 03 06](https://user-images.githubusercontent.com/73175330/204105152-9a98e637-fef9-4149-878c-71feed87293c.png)
![изображение](https://user-images.githubusercontent.com/73175330/204105218-8d22bd8f-e838-4a9a-83aa-b40044e03202.png)

**Comment by RinixGG** [comment]
Can you please upload this release to modrinth?

**Comment by SJKZ1-2565** [comment]
> Can you please upload this release to modrinth?

Sure but I'm still working on it
