### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by RinixGG** [SJKZ1-2565/CheesySlot#4]
Can you add support for all kinds of clickable blocks and entities such as chest, barrel, hopper, trapped chest, beacon, ender chest, chest minecart, hopper minecart and boat with chest

![Несохранённое изображение 1](https://user-images.githubusercontent.com/73175330/204655911-083e9017-0d8e-4f9e-95fc-c76c7fdd6369.jpg)

**Comment by SJKZ1-2565** [comment]
Sure!

**Comment by GxSarukaZ** [comment]
Can you make rainbow text?
