### ISSUE TITLE
Mod is incompatible with quilt loader

### ISSUE THREAD

**Issue by voidrinix** [SJKZ1-2565/CheesySlot#7]
![изображение](https://user-images.githubusercontent.com/73175330/206841044-b49a8d82-ede5-4aba-907b-c8c83d749329.png)

**Comment by SJKZ1-2565** [comment]
Update your quilt loader the fabric loader must be above 0.14.11

**Comment by voidrinix** [comment]
> Update your quilt loader the fabric loader must be above 0.14.11

I've installed the latest beta version but the issue is keeping

**Comment by SJKZ1-2565** [comment]
Well, you have to wait for quilt update newer version

**Comment by voidrinix** [comment]
> Well, you have to wait for quilt update newer version

okay
