### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by voidrinix** [SJKZ1-2565/CheesySlot#8]
Hello! I have some ideas that will be useful IMO:
1. Add option to change the rainbow effect speed
2. Add option to change scale of the shadow of text
3. Add numbers to villager's, wandering trader's and beacon's gui(screenshots)
(I'm sorry for bad english cuz it isn't my native language)
![изображение](https://user-images.githubusercontent.com/73175330/207718764-6310755d-661a-436a-8cf9-46d2e2be7238.png)
![изображение](https://user-images.githubusercontent.com/73175330/207718825-556c22f4-4ed1-4356-819e-f0c8ca50800b.png)
![изображение](https://user-images.githubusercontent.com/73175330/207719053-b5067e79-f059-4ad4-a177-f6bed4154e51.png)

**Comment by SJKZ1-2565** [comment]
It's ok I understand what you want
